kind: Pod
apiVersion: v1
metadata:
  name: write-pod
spec:
  containers:
    - name: write-pod
      image: busybox
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "touch /mnt/SUCCESS && exit 0 || exit 1"